### ISSUE TITLE
The CodaLab Challenge was down, could you repair it.

### ISSUE THREAD

**Issue by LeeXuefeng** [shreyashampali/HOnnotate#25]
The  CodaLab Challenge of HO3Dv2 was down, could you repair it. I want to do some work based on it, but it has been down frequently. Could U public the testing dataset like FreiHAND? It's too much trouble to upload for evaluation.

**Comment by zdforient** [comment]
v3 is down too, here is the error when I was trying to make submissions:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/codalab/tmpyH3pSc/run/program/evaluate.py", line 18, in <module>
    import open3d as o3d
ModuleNotFoundError: No module named 'open3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/codalab/tmpyH3pSc/run/program/evaluate.py", line 21, in <module>
    import open3d as o3d
  File "/opt/conda/lib/python3.9/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/opt/conda/lib/python3.9/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.9/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct
