### ISSUE TITLE
The F-scores results of the HO3D-v2 Codalab Challenge are all zeros

### ISSUE THREAD

**Issue by hxwork** [shreyashampali/HOnnotate#26]
Hi,

The F-scores results of the HO3D-v2 Codalab Challenge are all zeros. The maintainer of the Codalab said that the organizers could fix this easily, as described [here](https://github.com/codalab/codalab-competitions/issues/3263#issuecomment-1260821207). Could you please help us to fix this problem?

Best regards,
Hao

**Comment by Didayolo** [comment]
Link to the competition : https://codalab.lisn.upsaclay.fr/competitions/4318

The fix could simply to come back to the old scoring program and to put the competition docker image to `codalab/codalab-legacy:py2`.

**Comment by shreyashampali** [comment]
@Didayolo 
I tried the fix you suggested but got the same error as earlier below.

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/codalab/tmpIy7A1y/run/program/evaluate.py", line 19, in <module>
    import open3d as o3d
  File "/opt/conda/lib/python3.9/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/opt/conda/lib/python3.9/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.9/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/codalab/tmpIy7A1y/run/program/evaluate.py", line 22, in <module>
    import open3d as o3d
  File "/opt/conda/lib/python3.9/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/opt/conda/lib/python3.9/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.9/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct
```
it looks like it didnt pick py2!

**Comment by shreyashampali** [comment]
@Didayolo 
Figured out this was due to re-submitting. Everything works after reupload, thanks!

**Comment by hxwork** [comment]
Many thanks, it works now. I will close this issue.

**Comment by Didayolo** [comment]
Nice to hear!
